[QT-641] Improve actions/set-up-go output and speed
* Improve the action speed by removing uncessary `go list`'s for each
  module.
* Create a module for external deps that are required as part of CI but
  are not included in the build itself. This allows us to hook various
  CI deps into the same module cache.

Signed-off-by: Ryan Cragun <me@ryan.ec>

diff --git a/.github/actions/set-up-go/action.yml b/.github/actions/set-up-go/action.yml
--- a/.github/actions/set-up-go/action.yml
+++ b/.github/actions/set-up-go/action.yml
@@ -65,10 +65,10 @@ runs:
       shell: bash
       run: |
         git config --global url."https://${{ inputs.github-token }}@github.com".insteadOf https://github.com
-        for mod in $(find . -type f -name go.mod); do
-          pushd "$(dirname $mod)"
-            go list ./...
-            go list -test ./...
-            go mod download
-          popd
-        done
+        while IFS= read -r -d '' mod; do
+          echo "Downloading Go modules for $mod"
+          pushd "$(dirname "$mod")" > /dev/null || (echo "failed to push into module dir" && exit 1)
+            GOOS=linux GOARCH=amd64 go mod download -x
+          popd > /dev/null || (echo "failed to pop out of module dir" && exit 1)
+        done < <(find . -type f -name go.mod -print0)
+        du -h -d 1 ${{ steps.metadata.outputs.cache-path }}
